/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as R404RouteImport } from './routes/$404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GetStartedSsoCallbackRouteImport } from './routes/get-started/sso-callback'
import { Route as ApiGeneratePlanRouteImport } from './routes/api/generate-plan'

const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/$404',
  path: '/$404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedSsoCallbackRoute = GetStartedSsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => GetStartedRoute,
} as any)
const ApiGeneratePlanRoute = ApiGeneratePlanRouteImport.update({
  id: '/api/generate-plan',
  path: '/api/generate-plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/get-started': typeof GetStartedRouteWithChildren
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/get-started/sso-callback': typeof GetStartedSsoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/get-started': typeof GetStartedRouteWithChildren
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/get-started/sso-callback': typeof GetStartedSsoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/dashboard': typeof DashboardRoute
  '/get-started': typeof GetStartedRouteWithChildren
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/get-started/sso-callback': typeof GetStartedSsoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$404'
    | '/dashboard'
    | '/get-started'
    | '/api/generate-plan'
    | '/get-started/sso-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$404'
    | '/dashboard'
    | '/get-started'
    | '/api/generate-plan'
    | '/get-started/sso-callback'
  id:
    | '__root__'
    | '/'
    | '/$404'
    | '/dashboard'
    | '/get-started'
    | '/api/generate-plan'
    | '/get-started/sso-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DashboardRoute: typeof DashboardRoute
  GetStartedRoute: typeof GetStartedRouteWithChildren
  ApiGeneratePlanRoute: typeof ApiGeneratePlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$404': {
      id: '/$404'
      path: '/$404'
      fullPath: '/$404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started/sso-callback': {
      id: '/get-started/sso-callback'
      path: '/sso-callback'
      fullPath: '/get-started/sso-callback'
      preLoaderRoute: typeof GetStartedSsoCallbackRouteImport
      parentRoute: typeof GetStartedRoute
    }
    '/api/generate-plan': {
      id: '/api/generate-plan'
      path: '/api/generate-plan'
      fullPath: '/api/generate-plan'
      preLoaderRoute: typeof ApiGeneratePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GetStartedRouteChildren {
  GetStartedSsoCallbackRoute: typeof GetStartedSsoCallbackRoute
}

const GetStartedRouteChildren: GetStartedRouteChildren = {
  GetStartedSsoCallbackRoute: GetStartedSsoCallbackRoute,
}

const GetStartedRouteWithChildren = GetStartedRoute._addFileChildren(
  GetStartedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DashboardRoute: DashboardRoute,
  GetStartedRoute: GetStartedRouteWithChildren,
  ApiGeneratePlanRoute: ApiGeneratePlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
